import type { ThemeOption } from '../types';

export const themes: ThemeOption[] = [
	{
		id: 'dark_blue',
		name: 'Command Center Blue (Default)',
		styles: {
			'--color-bg-main': '#10141A',
			'--color-bg-panel': '#1A1D24',
			'--color-bg-dark': '#2A2F38',
			'--color-border': '#39414F',
			'--color-text-primary': '#E6EDF3',
			'--color-text-secondary': '#8D96A5',
			'--color-text-on-accent': '#FFFFFF',
			'--color-primary-red': '#DA3633',
			'--color-primary-red-glow': '#F85149',
			'--color-secondary-blue': '#3B82F6',
			'--color-secondary-blue-glow': '#58A6FF',
			'--color-secondary-blue-rgb': '59, 130, 246',
			'--color-priority-high': '#DA3633',
			'--color-priority-medium': '#F59E0B',
			'--color-priority-low': '#3B82F6',
		}
	},
	{
		id: 'midnight_purple',
		name: 'Midnight Purple',
		styles: {
			'--color-bg-main': '#12101b',
			'--color-bg-panel': '#1e1c2a',
			'--color-bg-dark': '#2f2c40',
			'--color-border': '#46425c',
			'--color-text-primary': '#e9e7f5',
			'--color-text-secondary': '#9a96b3',
			'--color-text-on-accent': '#FFFFFF',
			'--color-primary-red': '#e54b64',
			'--color-primary-red-glow': '#ff6b81',
			'--color-secondary-blue': '#8b5cf6',
			'--color-secondary-blue-glow': '#a78bfa',
			'--color-secondary-blue-rgb': '139, 92, 246',
			'--color-priority-high': '#e54b64',
			'--color-priority-medium': '#f59e0b',
			'--color-priority-low': '#8b5cf6',
		}
	},
	{
		id: 'forest_canopy',
		name: 'Forest Canopy',
		styles: {
			'--color-bg-main': '#0c1412',
			'--color-bg-panel': '#1a2421',
			'--color-bg-dark': '#2a3834',
			'--color-border': '#42544f',
			'--color-text-primary': '#e6f0ec',
			'--color-text-secondary': '#8da39b',
			'--color-text-on-accent': '#FFFFFF',
			'--color-primary-red': '#e57373',
			'--color-primary-red-glow': '#ef9a9a',
			'--color-secondary-blue': '#66bb6a',
			'--color-secondary-blue-glow': '#81c784',
			'--color-secondary-blue-rgb': '102, 187, 106',
			'--color-priority-high': '#e57373',
			'--color-priority-medium': '#ffd54f',
			'--color-priority-low': '#66bb6a',
		}
	},
	{
		id: 'arctic_wolf',
		name: 'Arctic Wolf',
		styles: {
			'--color-bg-main': '#0A0A0A',
			'--color-bg-panel': '#121212',
			'--color-bg-dark': '#161616',
			'--color-border': '#2a2a2a',
			'--color-text-primary': '#FFFFFF',
			'--color-text-secondary': '#C9C9C9',
			'--color-text-on-accent': '#FFFFFF',
			'--color-primary-red': '#888888',
			'--color-primary-red-glow': '#A0A0A0',
			'--color-secondary-blue': '#3B82F6',
			'--color-secondary-blue-glow': '#58A6FF',
			'--color-secondary-blue-rgb': '59, 130, 246',
			'--color-priority-high': '#DE5A5A',
			'--color-priority-medium': '#C9C9C9',
			'--color-priority-low': '#3B82F6',
		}
	},
	{
		id: 'crimson_dusk',
		name: 'Crimson Dusk',
		styles: {
			'--color-bg-main': '#1c1c1c',
			'--color-bg-panel': '#222',
			'--color-bg-dark': '#2a2a2a',
			'--color-border': '#3a3a3a',
			'--color-text-primary': '#f5eadd',
			'--color-text-secondary': '#d8cfc2',
			'--color-text-on-accent': '#1c1c1c',
			'--color-primary-red': '#DA3633',
			'--color-primary-red-glow': '#ff6b6b',
			'--color-secondary-blue': '#ff4500',
			'--color-secondary-blue-glow': '#ff7a3c',
			'--color-secondary-blue-rgb': '255, 69, 0',
			'--color-priority-high': '#DA3633',
			'--color-priority-medium': '#ff7a3c',
			'--color-priority-low': '#ffd27a',
		}
	}
];